### ISSUE TITLE
Operator controller pod is crashing if RedisExporter definition is absent into manifest ( OKD 4)

### ISSUE THREAD

**Issue by gialloguitar** [OT-CONTAINER-KIT/redis-operator#175]
We are using redis-operator installed via operator hub for  OKD 4.7 clusters
 
**OpenShift version 4.7.0-0.okd-2021-09-19-013247**
**redis-operator version: 0.8.0**

Unworking redis manifest:
```
# Source: redis/templates/redis.yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis-standalone
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 101m
        memory: 128Mi
    serviceType: ClusterIP
```
- We are applying  manifest (oc/kubectl or helm)

- Operator is creating Redis instance and then crashing  

- logs from crashed controller manager pod

```shell
2021-11-18T16:22:16.752Z	INFO	controllers.Redis	Reconciling opstree redis controller	{"Request.Namespace": "default", "Request.Name": "redis-standalone"}
E1118 16:22:16.752674       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 477 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1672800, 0x23e20c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1672800, 0x23e20c0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
redis-operator/k8sutils.generateRedisStandaloneParams(...)
	/workspace/k8sutils/redis-standalone.go:64
redis-operator/k8sutils.CreateStandAloneRedis(0xc0005598c0, 0xc0005598c0, 0x1a525e0)
	/workspace/k8sutils/redis-standalone.go:43 +0x584
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc0001ebd10, 0x1a2dec0, 0xc000a67ec0, 0xc00003e560, 0xa, 0xc00003e530, 0x10, 0xc000a67ec0, 0x40a27f, 0xc000030000, ...)
	/workspace/controllers/redis_controller.go:59 +0x328
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00037eb40, 0x1a2de00, 0xc000500100, 0x16c9e20, 0xc0001a2700)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00037eb40, 0x1a2de00, 0xc000500100, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1a2de00, 0xc000500100)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000eff50)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a31f50, 0x19f76a0, 0xc0009bb260, 0xc000500101, 0xc000602000)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000eff50, 0x3b9aca00, 0x0, 0x1, 0xc000602000)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1a2de00, 0xc000500100, 0xc0009af590, 0x3b9aca00, 0x0, 0xc000519201)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1a2de00, 0xc000500100, 0xc0009af590, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4e7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x152d5c4]

goroutine 477 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1672800, 0x23e20c0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
redis-operator/k8sutils.generateRedisStandaloneParams(...)
	/workspace/k8sutils/redis-standalone.go:64
redis-operator/k8sutils.CreateStandAloneRedis(0xc0005598c0, 0xc0005598c0, 0x1a525e0)
	/workspace/k8sutils/redis-standalone.go:43 +0x584
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc0001ebd10, 0x1a2dec0, 0xc000a67ec0, 0xc00003e560, 0xa, 0xc00003e530, 0x10, 0xc000a67ec0, 0x40a27f, 0xc000030000, ...)
	/workspace/controllers/redis_controller.go:59 +0x328
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00037eb40, 0x1a2de00, 0xc000500100, 0x16c9e20, 0xc0001a2700)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00037eb40, 0x1a2de00, 0xc000500100, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1a2de00, 0xc000500100)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000eff50)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a31f50, 0x19f76a0, 0xc0009bb260, 0xc000500101, 0xc000602000)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000eff50, 0x3b9aca00, 0x0, 0x1, 0xc000602000)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1a2de00, 0xc000500100, 0xc0009af590, 0x3b9aca00, 0x0, 0xc000519201)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1a2de00, 0xc000500100, 0xc0009af590, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4e7
```

I found out that it will happen if `redisExporter` field  is absent into manifest

Could you please investigate those behavior and make notice about '-required-' field for this object 

```
shell
oc explain redis.spec                                                                                             
KIND:     Redis
VERSION:  redis.redis.opstreelabs.in/v1beta1

RESOURCE: spec <Object>

DESCRIPTION:
     RedisSpec defines the desired state of Redis

FIELDS:
   affinity	<Object>
     Affinity is a group of affinity scheduling rules.

   kubernetesConfig	<Object> -required-
     KubernetesConfig will be the JSON struct for Basic Redis Config

   nodeSelector	<map[string]string>

   priorityClassName	<string>

   redisConfig	<Object>
     RedisConfig defines the external configuration of Redis

   redisExporter	<Object>
     RedisExporter interface will have the information for redis exporter
     related stuff

   securityContext	<Object>
     PodSecurityContext holds pod-level security attributes and common container
     settings. Some fields are also present in container.securityContext. Field
     values of container.securityContext take precedence over field values of
     PodSecurityContext.

   storage	<Object>
     Storage is the inteface to add pvc and pv support in redis

   tolerations	<[]Object>
```

**Comment by dm3ch** [comment]
I faced same issue on k8s, when I have tried to enable exporter.

But I don't see this error on operator 0.9.0. 0.9.0 is released but seems it wasn't published as a new version of helm chart.

**Comment by iamabhishek-dubey** [comment]
https://github.com/OT-CONTAINER-KIT/helm-charts/releases

We have released it.
