### ISSUE TITLE
SIGSEGV: segmentation violation in v0.14.0 with simple spec

### ISSUE THREAD

**Issue by Jessev6** [OT-CONTAINER-KIT/redis-operator#462]
**What version of redis operator are you using?**

redis-operator version: 0.14.0

**Does this issue reproduce with the latest release?**
Yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9-gke.3200", GitCommit:"92ea556d4e7418d0e7b5db1ee576a73f8fc47e91", GitTreeState:"clean", BuildDate:"2023-01-20T09:29:29Z", GoVersion:"go1.18.9b7", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**
Tried to deploy a redis cluster with the latest version of the operator. Previously I was using v0.10.3 and this was working fine. I upgraded the helm chart to 0.14.0 and tried to recreate the redis cluster from scratch and the Redis-operator keeps crashing.

**What did you expect to see?**
A working redis cluster.

**What did you see instead?**
The redis resource is created in the cluster but the components are not being created because the operator is crashing.

Redis Cluster Spec:
```yaml
apiVersion: v1
items:
- apiVersion: redis.redis.opstreelabs.in/v1beta1
  kind: Redis
  metadata:
    creationTimestamp: "2023-03-17T14:06:20Z"
    finalizers:
    - redisFinalizer
    generation: 2
    name: example-redis
    namespace: default
    resourceVersion: "5901"
    uid: 63bb700d-9fc1-4b46-8b8e-8ae873aaa4bd
  spec:
    kubernetesConfig:
      image: quay.io/opstree/redis:v6.2.5
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
    redisExporter:
      env: []
      image: ""
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1m
          memory: 1Mi
        requests:
          cpu: 1m
          memory: 1Mi
    storage:
      volumeClaimTemplate:
        metadata: {}
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: standard
        status: {}
kind: List
metadata:
  resourceVersion: ""
```

Logs from the operator:
```
{"level":"info","ts":1679062062.238795,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1679062062.2402163,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1679062062.2413287,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":1679062062.2419062,"msg":"Starting server","kind":"health probe","addr":"[::]:8081"}
I0317 14:07:42.242135       1 leaderelection.go:248] attempting to acquire leader lease redis-operator/6cab913b.redis.opstreelabs.in...
I0317 14:07:58.102663       1 leaderelection.go:258] successfully acquired lease redis-operator/6cab913b.redis.opstreelabs.in
{"level":"info","ts":1679062078.1029453,"logger":"controller.redis","msg":"Starting EventSource","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","source":"kind source: *v1beta1.Redis"}
{"level":"info","ts":1679062078.10299,"logger":"controller.redis","msg":"Starting Controller","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis"}
{"level":"info","ts":1679062078.1045394,"logger":"controller.rediscluster","msg":"Starting EventSource","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster","source":"kind source: *v1beta1.RedisCluster"}
{"level":"info","ts":1679062078.1049469,"logger":"controller.rediscluster","msg":"Starting Controller","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster"}
{"level":"info","ts":1679062078.2043803,"logger":"controller.redis","msg":"Starting workers","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"Redis","worker count":1}
{"level":"info","ts":1679062078.2051206,"logger":"controllers.Redis","msg":"Reconciling opstree redis controller","Request.Namespace":"default","Request.Name":"example-redis"}
{"level":"info","ts":1679062078.2064607,"logger":"controller.rediscluster","msg":"Starting workers","reconciler group":"redis.redis.opstreelabs.in","reconciler kind":"RedisCluster","worker count":1}
{"level":"info","ts":1679062078.2114847,"logger":"controller_redis","msg":"Redis statefulset get action failed","Request.StatefulSet.Namespace":"default","Request.StatefulSet.Name":"example-redis"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1415795]

goroutine 267 [running]:
redis-operator/k8sutils.getProbeInfo(...)
        /workspace/k8sutils/statefulset.go:414
redis-operator/k8sutils.generateContainerDef({0xc0005b5500, 0x0}, {{0xc0005edec0, 0x1c}, {0xc0005b5514, 0xc}, 0xc0002a6700, {0x0, 0x0}, {0xc0005b5570, ...}, ...}, ...)
        /workspace/k8sutils/statefulset.go:291 +0x115
redis-operator/k8sutils.generateStatefulSetsDef({{0xc0005b5500, 0xd}, {0x0, 0x0}, {0xc0005b54f6, 0x7}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        /workspace/k8sutils/statefulset.go:195 +0x1b6
redis-operator/k8sutils.CreateOrUpdateStateFul({_, _}, {{0xc0005b5500, 0xd}, {0x0, 0x0}, {0xc0005b54f6, 0x7}, {0x0, 0x0}, ...}, ...)
        /workspace/k8sutils/statefulset.go:63 +0x18a
redis-operator/k8sutils.CreateStandaloneRedis(0xc00000a960)
        /workspace/k8sutils/redis-standalone.go:40 +0x385
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc00062a900, {0xc000347140, 0x155e1a0}, {{{0xc0005b54f6, 0x1668f60}, {0xc0005b5500, 0x30}}})
        /workspace/controllers/redis_controller.go:63 +0x29c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0005d9130, {0x1942e58, 0xc000347140}, {{{0xc0005b54f6, 0x1668f60}, {0xc0005b5500, 0x413a94}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0005d9130, {0x1942db0, 0xc000632100}, {0x15b3980, 0xc000445a20})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0005d9130, {0x1942db0, 0xc000632100})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by tungtt1006** [comment]
Same bug here

**Comment by shubham-cmyk** [comment]
@alperbas Is raised suddenly ??

**Comment by alperbas** [comment]
@shubham-cmyk yes. It was working fine 3 days ago and we had holidays in between then and today. So I know no one touched it. After restarts operator started to crash. With `imagePullPolicy: Always` I assume it just pulled the latest updated image. I had to roll back the image version to v0.13.0 to get it working again.

The error is as below.



```
 {"level":"info","ts":1681497262.283119,"logger":"controller_redis","msg":"Redis statefulset get action was successful","Request.StatefulSet.Namespace":"<redacted>","Request.StatefulSet.Name":"<redacted>"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1425871]

goroutine 457 [running]:
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.generateStatefulSetsDef({{0xc000a169d0, 0xb}, {0x0, 0x0}, {0xc0004e0a80, 0x22}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/workspace/k8sutils/statefulset.go:210 +0x51
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.CreateOrUpdateStateFul({_, _}, {{0xc000a169d0, 0xb}, {0x0, 0x0}, {0xc0004e0a80, 0x22}, {0x0, 0x0}, ...}, ...)
	/workspace/k8sutils/statefulset.go:89 +0x1ad
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.CreateStandaloneRedis(0xc0009a2000)
	/workspace/k8sutils/redis-standalone.go:56 +0x3f8
github.com/OT-CONTAINER-KIT/redis-operator/controllers.(*RedisReconciler).Reconcile(0xc000756150, {0xc00098d0b0, 0x15742c0}, {{{0xc0004e0a80, 0x167fea0}, {0xc000a169d0, 0x30}}})
	/workspace/controllers/redis_controller.go:66 +0x2c8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0000b4000, {0x195e0d8, 0xc00098d0b0}, {{{0xc0004e0a80, 0x167fea0}, {0xc000a169d0, 0x413a34}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000b4000, {0x195e030, 0xc0006f4080}, {0x15ca160, 0xc0003347a0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000b4000, {0x195e030, 0xc0006f4080})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
```

**Comment by shubham-cmyk** [comment]
@alperbas I have to revert a PR can you recheck it? The error was raised due to the automated release of the docker image on every merge which should be stopped.

**Comment by alperbas** [comment]
@shubham-cmyk thanks. Image v0.14.0 is not crashing anymore.

**Comment by shubham-cmyk** [comment]
@Jessev6 
Can you try to update the redis image version to` image: quay.io/opstree/redis:v7.0.5`
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/redis-standalone.yaml
and use the operator v0.14.0
