### ISSUE TITLE
Goroutine in operator when deploying a `Kind: Redis`

### ISSUE THREAD

**Issue by anthr76** [OT-CONTAINER-KIT/redis-operator#63]
Operator logs:

```
I0504 00:23:03.628139       1 request.go:645] Throttling request took 1.042982648s, request: GET:https://10.42.0.1:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
2021-05-04T00:23:04.578Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2021-05-04T00:23:04.579Z        INFO    setup   starting manager
I0504 00:23:04.579565       1 leaderelection.go:243] attempting to acquire leader lease  database/6cab913b.redis.opstreelabs.in...
2021-05-04T00:23:04.580Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
I0504 00:23:22.047400       1 leaderelection.go:253] successfully acquired lease database/6cab913b.redis.opstreelabs.in
2021-05-04T00:23:22.047Z        INFO    controller-runtime.manager.controller.redis     Starting EventSource    {"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "Redis", "source": "kind source: /, Kind="}
2021-05-04T00:23:22.048Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ConfigMap","namespace":"database","name":"6cab913b.redis.opstreelabs.in","uid":"d9daf262-63e7-42fd-9b62-995964983ef1","apiVersion":"v1","resourceVersion":"3673998"}, "reason": "LeaderElection", "message": "redis-operator-78c558545b-pqmfm_cb6bf157-0cc5-4dce-967f-523294df3b3b became leader"}
2021-05-04T00:23:22.048Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"Lease","namespace":"database","name":"6cab913b.redis.opstreelabs.in","uid":"4b2716af-6c7d-4b3a-9ac4-0b0a23304cc6","apiVersion":"coordination.k8s.io/v1","resourceVersion":"3673999"}, "reason": "LeaderElection", "message": "redis-operator-78c558545b-pqmfm_cb6bf157-0cc5-4dce-967f-523294df3b3b became leader"}
2021-05-04T00:23:22.148Z        INFO    controller-runtime.manager.controller.redis     Starting Controller     {"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "Redis"}
2021-05-04T00:23:22.148Z        INFO    controller-runtime.manager.controller.redis     Starting workers        {"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "Redis", "worker count": 1}
2021-05-04T00:23:22.148Z        INFO    controllers.Redis       Reconciling Opstree Redis controller    {"Request.Namespace": "networking", "Request.Name": "authelia-redis"}
E0504 00:23:22.249510       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 319 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x164b280, 0x239bed0)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x164b280, 0x239bed0)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
redis-operator/k8sutils.FinalContainerDef(0xc00040e800, 0x180b234, 0x6, 0x1809494, 0x1, 0x180b234)
        /workspace/k8sutils/statefulset.go:170 +0x14f
redis-operator/k8sutils.GenerateStateFulSetsDef(0xc00040e800, 0xc0005ba900, 0x180b234, 0x6, 0xc0005b9484, 0xc0005bed60)
        /workspace/k8sutils/statefulset.go:41 +0x2f2
redis-operator/k8sutils.CreateRedisMaster(0xc00040e800)
        /workspace/k8sutils/statefulset.go:227 +0x185
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc00053a030, 0x19fd7c0, 0xc000581830, 0xc00003e370, 0xa, 0xc00003e360, 0xe, 0xc000581830, 0x40a27f, 0xc000030000, ...)
        /workspace/controllers/redis_controller.go:82 +0x4f5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00042b5e0, 0x19fd700, 0xc00044c000, 0x16a2080, 0xc0004e5e60)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00042b5e0, 0x19fd700, 0xc00044c000, 0xc0000a3e00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x19fd700, 0xc00044c000)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000a3f50)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000643f50, 0x19c73c0, 0xc000525c50, 0xc00044c001, 0xc000212300)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000a3f50, 0x3b9aca00, 0x0, 0x1, 0xc000212300)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x19fd700, 0xc00044c000, 0xc000526450, 0x3b9aca00, 0x0, 0x1)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x19fd700, 0xc00044c000, 0xc000526450, 0x3b9aca00)
        /go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4e7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15124cf]
```

Redis CRD

```yml
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: authelia-redis
  namespace: networking
spec:
  mode: cluster
  size: 3
  global:
    image: quay.io/opstree/redis:v6.2
    imagePullPolicy: IfNotPresent
    existingPasswordSecret:
      name: authelia-secrets
      key: REDIS_PASSWORD
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  master:
    service:
      type: ClusterIP
    redisConfig: {}
  slave:
    service:
      type: ClusterIP
    redisConfig: {}
  service:
    type: ClusterIP
  redisConfig: {}
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: cstor-replica-pool
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
```

If there's any if to add I'd be happy to help.

**Comment by iamabhishek-dubey** [comment]
```yaml
  redisExporter:
    enabled: false # or true
```

This block is missing in your configuration, that's what causing this issue

**Comment by anthr76** [comment]
That was indeed it! Thanks for the quick reply.

**Comment by xkwangcn** [comment]
@iamabhishek-dubey Hello, I encounter the same problem. 
This is my reltated yaml:
```

{

    "apiVersion":"redis.redis.opstreelabs.in/v1beta1",
    "kind":"Redis",
    "metadata":{
        "name":"redis-standalone"
    },
    "spec":{
        "redisExporter":{
            "enabled":true,
            "image":"image-registry.openshift-image-registry.svc:5000/openshift/redis-exporter:latest",
            "imagePullPolicy":"Always"
        },
        "kubernetesConfig":{
            "image":"docker.io/library/redis:6.2-alpine",
            "imagePullPolicy":"IfNotPresent",
            "redisSecret":{
                "name":"redis-secret",
                "key":"password"
            },
            "serviceType":"LoadBalancer"
        },
        "redisConfig":{
        },
        "storage":{
            "volumeClaimTemplate":{
                "spec":{
                    "accessModes":[
                        "ReadWriteOnce"
                    ],
                    "resources":{
                        "requests":{
                            "storage":"1Gi"
                        }
                    }
                }
            }
        }
    }

}
{

    "apiVersion":"redis.redis.opstreelabs.in/v1beta1",
    "kind":"Redis",
    "metadata":{
        "name":"redis-standalone"
    },
    "spec":{
        "redisExporter":{
            "enabled":true,
            "image":"image-registry.openshift-image-registry.svc:5000/openshift/redis-exporter:latest",
            "imagePullPolicy":"Always"
        },
        "kubernetesConfig":{
            "image":"docker.io/library/redis:6.2-alpine",
            "imagePullPolicy":"IfNotPresent",
            "redisSecret":{
                "name":"redis-secret",
                "key":"password"
            },
            "serviceType":"LoadBalancer"
        },
        "redisConfig":{
        },
        "storage":{
            "volumeClaimTemplate":{
                "spec":{
                    "accessModes":[
                        "ReadWriteOnce"
                    ],
                    "resources":{
                        "requests":{
                            "storage":"1Gi"
                        }
                    }
                }
            }
        }
    }

}
```
My redisExporter is set true here. My error is:
```
oc logs pod/redis-operator-6b4cc995cf-2msfv 
I0811 06:14:34.549566       1 request.go:645] Throttling request took 1.032909998s, request: GET:https://172.30.0.1:443/apis/certificates.k8s.io/v1?timeout=32s
2021-08-11T06:14:36.460Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2021-08-11T06:14:36.460Z	INFO	setup	starting manager
I0811 06:14:36.460958       1 leaderelection.go:243] attempting to acquire leader lease  openshift-operators/6cab913b.redis.opstreelabs.in...
2021-08-11T06:14:36.460Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
I0811 06:14:51.544891       1 leaderelection.go:253] successfully acquired lease openshift-operators/6cab913b.redis.opstreelabs.in
2021-08-11T06:14:51.544Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"ConfigMap","namespace":"openshift-operators","name":"6cab913b.redis.opstreelabs.in","uid":"f4e6b5e3-f759-47df-a374-1c67348758cc","apiVersion":"v1","resourceVersion":"83602926"}, "reason": "LeaderElection", "message": "redis-operator-6b4cc995cf-2msfv_3a3f6ea0-059c-496d-9118-1a9ce49e36cd became leader"}
2021-08-11T06:14:51.545Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"Lease","namespace":"openshift-operators","name":"6cab913b.redis.opstreelabs.in","uid":"5f403f6e-861e-4f25-b27b-f76e44a6c95d","apiVersion":"coordination.k8s.io/v1","resourceVersion":"83602927"}, "reason": "LeaderElection", "message": "redis-operator-6b4cc995cf-2msfv_3a3f6ea0-059c-496d-9118-1a9ce49e36cd became leader"}
2021-08-11T06:14:51.545Z	INFO	controller-runtime.manager.controller.rediscluster	Starting EventSource	{"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "RedisCluster", "source": "kind source: /, Kind="}
2021-08-11T06:14:51.545Z	INFO	controller-runtime.manager.controller.redis	Starting EventSource	{"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "Redis", "source": "kind source: /, Kind="}
2021-08-11T06:14:51.645Z	INFO	controller-runtime.manager.controller.rediscluster	Starting Controller	{"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "RedisCluster"}
2021-08-11T06:14:51.645Z	INFO	controller-runtime.manager.controller.rediscluster	Starting workers	{"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "RedisCluster", "worker count": 1}
2021-08-11T06:14:51.645Z	INFO	controller-runtime.manager.controller.redis	Starting Controller	{"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "Redis"}
2021-08-11T06:14:51.645Z	INFO	controller-runtime.manager.controller.redis	Starting workers	{"reconciler group": "redis.redis.opstreelabs.in", "reconciler kind": "Redis", "worker count": 1}
2021-08-11T06:14:51.646Z	INFO	controllers.Redis	Reconciling opstree redis controller	{"Request.Namespace": "openshift-operators", "Request.Name": "redis"}
2021-08-11T06:14:51.653Z	INFO	controller_redis	Redis statefulset get action failed	{"Request.StateFulSet.Namespace": "openshift-operators", "Request.StateFulSet.Name": "redis"}
E0811 06:14:51.653332       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 399 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1167c80, 0x1ee8b60)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0x8a
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0xa8
panic(0x1167c80, 0x1ee8b60)
	/usr/local/go/src/runtime/panic.go:969 +0x16e
redis-operator/k8sutils.generateContainerDef(0xc0000af3a0, 0x5, 0xc000265260, 0x22, 0xc0000af430, 0xc, 0x0, 0xc0004c6910, 0x50, 0xc0000af448, ...)
	/workspace/k8sutils/statefulset.go:147 +0x3f0
redis-operator/k8sutils.generateStateFulSetsDef(0xc0000af3a0, 0x5, 0x0, 0x0, 0xc0006e56a0, 0x13, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/k8sutils/statefulset.go:104 +0x84
redis-operator/k8sutils.CreateOrUpdateStateFul(0xc0006e56a0, 0x13, 0xc0000af3a0, 0x5, 0x0, 0x0, 0xc0006e56a0, 0x13, 0x0, 0x0, ...)
	/workspace/k8sutils/statefulset.go:50 +0x1f8
redis-operator/k8sutils.CreateStandAloneRedis(0xc00033e900, 0xc00033e900, 0x154b5c0)
	/workspace/k8sutils/redis-standalone.go:40 +0x5b4
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc00046c6f0, 0x1526a40, 0xc00044af90, 0xc0006e56a0, 0x13, 0xc0000af3a0, 0x5, 0xc00044af90, 0x1, 0x0, ...)
	/workspace/controllers/redis_controller.go:59 +0x2de
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000c5b80, 0x1526980, 0xc0004bc240, 0x11bf180, 0xc0002b3800)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x2ae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000c5b80, 0x1526980, 0xc0004bc240, 0xc000550753)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x206
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1526980, 0xc0004bc240)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4c
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00055e760)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x56
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0004b3f60, 0x14f00e0, 0xc000687320, 0x100000000000000, 0xc0001001e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0x9c
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00055e760, 0x3b9aca00, 0x0, 0x100000000000000, 0xc0001001e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1526980, 0xc0004bc240, 0xc0004edc00, 0x3b9aca00, 0x0, 0x100000000000000)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa0
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1526980, 0xc0004bc240, 0xc0004edc00, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x48
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x434
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1023010]

goroutine 399 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x162
panic(0x1167c80, 0x1ee8b60)
	/usr/local/go/src/runtime/panic.go:969 +0x16e
redis-operator/k8sutils.generateContainerDef(0xc0000af3a0, 0x5, 0xc000265260, 0x22, 0xc0000af430, 0xc, 0x0, 0xc0004c6910, 0x50, 0xc0000af448, ...)
	/workspace/k8sutils/statefulset.go:147 +0x3f0
redis-operator/k8sutils.generateStateFulSetsDef(0xc0000af3a0, 0x5, 0x0, 0x0, 0xc0006e56a0, 0x13, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/k8sutils/statefulset.go:104 +0x84
redis-operator/k8sutils.CreateOrUpdateStateFul(0xc0006e56a0, 0x13, 0xc0000af3a0, 0x5, 0x0, 0x0, 0xc0006e56a0, 0x13, 0x0, 0x0, ...)
	/workspace/k8sutils/statefulset.go:50 +0x1f8
redis-operator/k8sutils.CreateStandAloneRedis(0xc00033e900, 0xc00033e900, 0x154b5c0)
	/workspace/k8sutils/redis-standalone.go:40 +0x5b4
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc00046c6f0, 0x1526a40, 0xc00044af90, 0xc0006e56a0, 0x13, 0xc0000af3a0, 0x5, 0xc00044af90, 0x1, 0x0, ...)
	/workspace/controllers/redis_controller.go:59 +0x2de
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000c5b80, 0x1526980, 0xc0004bc240, 0x11bf180, 0xc0002b3800)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x2ae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000c5b80, 0x1526980, 0xc0004bc240, 0xc000550753)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x206
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1526980, 0xc0004bc240)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4c
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00055e760)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x56
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0004b3f60, 0x14f00e0, 0xc000687320, 0x100000000000000, 0xc0001001e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0x9c
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00055e760, 0x3b9aca00, 0x0, 0x100000000000000, 0xc0001001e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1526980, 0xc0004bc240, 0xc0004edc00, 0x3b9aca00, 0x0, 0x100000000000000)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa0
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1526980, 0xc0004bc240, 0xc0004edc00, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x48
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x434
```
Could you help me about this problem? Thank you very much.

**Comment by xkwangcn** [comment]
My issue solved by give more memory on my cluster. Give this info for other friend who has same error. Thank you.
