### ISSUE TITLE
arm64 An environment installation error occurred 

### ISSUE THREAD

**Issue by wu1069805284** [OT-CONTAINER-KIT/redis-operator#741]
{"level":"info","ts":1704785693.1844518,"logger":"controllers.RedisCluster","msg":"Reconciling opstree redis Cluster controller","Request.Namespace":"ot-operators","Request.Name":"redis-cluster"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xff504c]

goroutine 483 [running]:
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.generateRedisClusterParams(0x4000d0c840, 0x3, 0x0, {{0x132e001, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x40006183a8, ...})
	/workspace/k8sutils/redis-cluster.go:33 +0xac
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.RedisClusterSTS.CreateRedisClusterSetup({{0x132e001, 0x6}, 0x0, 0x0, 0x0, 0x0, 0x40006183a8, 0x40006183f0, 0x0, 0x0}, ...)
	/workspace/k8sutils/redis-cluster.go:218 +0x298
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.CreateRedisLeader(0x4000d0c840)
	/workspace/k8sutils/redis-cluster.go:167 +0xac
github.com/OT-CONTAINER-KIT/redis-operator/controllers.(*RedisClusterReconciler).Reconcile(0x4000934a80, {0x1552258, 0x400092b170}, {{{0x4000c0c840, 0xc}, {0x4000c0c830, 0xd}}})
	/workspace/controllers/rediscluster_controller.go:105 +0x3e4
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x4000158e70, {0x1552258, 0x400092b0b0}, {{{0x4000c0c840, 0xc}, {0x4000c0c830, 0xd}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x22c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x4000158e70, {0x15521b0, 0x400092c900}, {0x11b9ac0, 0x40003dd720})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x2ac
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x4000158e70, {0x15521b0, 0x400092c900})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x1d4
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0x4000a84030, 0x4000158e70, {0x15521b0, 0x400092c900})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x60
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x324

**Comment by drivebyer** [comment]
Could you provide more info? such as operator version && yamls
