### ISSUE TITLE
start redis-cluster  operator error

### ISSUE THREAD

**Issue by dxygit1** [OT-CONTAINER-KIT/redis-operator#948]
I encountered an error with the operator while deploying the Redis cluster.

operator  version:  0.16.0
operator error

```bash
{"level":"info","ts":"2024-05-23T03:20:10Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"rediscluster","controllerGroup":"redis.redis.opstreelabs.in","controllerKind":"RedisCluster","RedisCluster":{"name":"redis-cluster","namespace":"redis"},"namespace":"redis","name":"redis-cluster","reconcileID":"301f65b4-9480-4448-b806-c5333b973dbb"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x173c3de]

goroutine 150 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x1977a80?, 0x2c38b50?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.generateRedisClusterParams(_, _, _, {{0x1bf92d6, 0x6}, 0x0, 0x0, 0x0, 0x0, 0xc000304a50, ...})
        /workspace/k8sutils/redis-cluster.go:38 +0x7e
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.RedisClusterSTS.CreateRedisClusterSetup({{0x1bf92d6, 0x6}, 0x0, 0x0, 0x0, 0x0, 0xc000304a50, 0xc000304a68, 0x0, 0x0}, ...)
        /workspace/k8sutils/redis-cluster.go:275 +0x6f8
github.com/OT-CONTAINER-KIT/redis-operator/k8sutils.CreateRedisLeader(0x1bf92d6?, {0x1eaa610?, 0xc00027e9c0?})
        /workspace/k8sutils/redis-cluster.go:224 +0xf8
github.com/OT-CONTAINER-KIT/redis-operator/controllers.(*RedisClusterReconciler).Reconcile(0xc0003f65f0, {0x1e90ed0, 0xc0003fa5a0}, {{{0xc000562236?, 0x5?}, {0xc000562240?, 0xc0004fdd48?}}})
        /workspace/controllers/rediscluster_controller.go:125 +0x5fb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1e93f90?, {0x1e90ed0?, 0xc0003fa5a0?}, {{{0xc000562236?, 0xb?}, {0xc000562240?, 0x0?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00026e280, {0x1e90f08, 0xc000152960}, {0x1a2cdc0?, 0xc0002ee5a0?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316 +0x3cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00026e280, {0x1e90f08, 0xc000152960})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266 +0x1c9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 84
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:223 +0x565
```

**Comment by dxygit1** [comment]
#921  Is this the same issue? In which version was this fixed? I see that version 0.17.0 still has this issue.
